// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package abstract

import (
	"context"
	"reflect"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/executor/shardruntime"
	"github.com/vektah/gqlparser/v2/ast"
)

const splitScope = "github.com/99designs/gqlgen/codegen/testserver/splitpackages"

var type_AbstractInterface = &shardruntime.ObjectChildLookup{
	TypeName: "AbstractInterface",
	Kind:     ast.Interface,
}
var type_AbstractUnion = &shardruntime.ObjectChildLookup{
	TypeName: "AbstractUnion",
	Kind:     ast.Union,
}
var type_ID = &shardruntime.ObjectChildLookup{
	TypeName: "ID",
	Kind:     ast.Scalar,
}
var type_Int = &shardruntime.ObjectChildLookup{
	TypeName: "Int",
	Kind:     ast.Scalar,
}
var type_String = &shardruntime.ObjectChildLookup{
	TypeName: "String",
	Kind:     ast.Scalar,
}

func init() {
	shardruntime.RegisterObject(splitScope, "InterfaceMemberA", func(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
		return _InterfaceMemberA(ctx, ec, sel, obj)
	})
	shardruntime.RegisterObject(splitScope, "InterfaceMemberB", func(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
		return _InterfaceMemberB(ctx, ec, sel, obj)
	})
	shardruntime.RegisterObject(splitScope, "UnionMemberA", func(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
		return _UnionMemberA(ctx, ec, sel, obj)
	})
	shardruntime.RegisterObject(splitScope, "UnionMemberB", func(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
		return _UnionMemberB(ctx, ec, sel, obj)
	})
}

var interfaceMemberAImplementors = []string{"InterfaceMemberA", "AbstractInterface"}

func _InterfaceMemberA(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
	fields := graphql.CollectFields(ec.GetOperationContext(), sel, interfaceMemberAImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("InterfaceMemberA")
		case "id":
			out.Values[i] = ec.ResolveField(ctx, "InterfaceMemberA", "id", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "a":
			out.Values[i] = ec.ResolveField(ctx, "InterfaceMemberA", "a", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	ec.AddDeferred(int32(len(deferred)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

var interfaceMemberBImplementors = []string{"InterfaceMemberB", "AbstractInterface"}

func _InterfaceMemberB(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
	fields := graphql.CollectFields(ec.GetOperationContext(), sel, interfaceMemberBImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("InterfaceMemberB")
		case "id":
			out.Values[i] = ec.ResolveField(ctx, "InterfaceMemberB", "id", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		case "b":
			out.Values[i] = ec.ResolveField(ctx, "InterfaceMemberB", "b", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	ec.AddDeferred(int32(len(deferred)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

var unionMemberAImplementors = []string{"UnionMemberA", "AbstractUnion"}

func _UnionMemberA(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
	fields := graphql.CollectFields(ec.GetOperationContext(), sel, unionMemberAImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("UnionMemberA")
		case "a":
			out.Values[i] = ec.ResolveField(ctx, "UnionMemberA", "a", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	ec.AddDeferred(int32(len(deferred)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

var unionMemberBImplementors = []string{"UnionMemberB", "AbstractUnion"}

func _UnionMemberB(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, obj any) graphql.Marshaler {
	fields := graphql.CollectFields(ec.GetOperationContext(), sel, unionMemberBImplementors)

	out := graphql.NewFieldSet(fields)
	deferred := make(map[string]*graphql.FieldSet)
	for i, field := range fields {
		switch field.Name {
		case "__typename":
			out.Values[i] = graphql.MarshalString("UnionMemberB")
		case "b":
			out.Values[i] = ec.ResolveField(ctx, "UnionMemberB", "b", field, obj)
			if out.Values[i] == graphql.Null {
				out.Invalids++
			}
		default:
			panic("unknown field " + strconv.Quote(field.Name))
		}
	}
	out.Dispatch(ctx)
	if out.Invalids > 0 {
		return graphql.Null
	}

	ec.AddDeferred(int32(len(deferred)))

	for label, dfs := range deferred {
		ec.ProcessDeferredGroup(graphql.DeferredGroup{
			Label:    label,
			Path:     graphql.GetPath(ctx),
			FieldSet: dfs,
			Context:  ctx,
		})
	}

	return out
}

// split_codecs_.gotpl — marshal
func marshalNID2string(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	_ = sel
	v := value.(string)
	res := graphql.MarshalID(v)
	if res == graphql.Null {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
	}
	return res
}

// split_codecs_.gotpl — marshal
func marshalNInt2int(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	_ = sel
	v := value.(int)
	res := graphql.MarshalInt(v)
	if res == graphql.Null {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
	}
	return res
}

// split_codecs_.gotpl — marshal
func marshalNString2string(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	_ = sel
	v := value.(string)
	res := graphql.MarshalString(v)
	if res == graphql.Null {
		if !graphql.HasFieldError(ctx, graphql.GetFieldContext(ctx)) {
			graphql.AddErrorf(ctx, "the requested element is null which the schema does not allow")
		}
	}
	return res
}

// split_codecs_.gotpl — marshal
func marshalOAbstractInterface2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋsplitpackagesᚋmodelᚐAbstractInterface(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	if value == nil {
		return graphql.Null
	}
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		return graphql.Null
	}
	if rv.Kind() == reflect.Struct {
		ptr := reflect.New(rv.Type())
		ptr.Elem().Set(rv)
		value = ptr.Interface()
	}
	handler, ok := shardruntime.LookupObject(splitScope, "AbstractInterface")
	if !ok {
		panic("missing object shard handler for AbstractInterface")
	}
	return handler(ctx, ec, sel, value)
}

// split_codecs_.gotpl — marshal
func marshalOAbstractUnion2githubᚗcomᚋ99designsᚋgqlgenᚋcodegenᚋtestserverᚋsplitpackagesᚋmodelᚐAbstractUnion(ctx context.Context, ec shardruntime.ObjectExecutionContext, sel ast.SelectionSet, value any) graphql.Marshaler {
	if value == nil {
		return graphql.Null
	}
	rv := reflect.ValueOf(value)
	if rv.Kind() == reflect.Ptr && rv.IsNil() {
		return graphql.Null
	}
	if rv.Kind() == reflect.Struct {
		ptr := reflect.New(rv.Type())
		ptr.Elem().Set(rv)
		value = ptr.Interface()
	}
	handler, ok := shardruntime.LookupObject(splitScope, "AbstractUnion")
	if !ok {
		panic("missing object shard handler for AbstractUnion")
	}
	return handler(ctx, ec, sel, value)
}

// split_codecs_.gotpl — unmarshal
func unmarshalNID2string(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	res, err := graphql.UnmarshalID(value)
	return res, graphql.ErrorOnPath(ctx, err)
}

// split_codecs_.gotpl — unmarshal
func unmarshalNInt2int(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	res, err := graphql.UnmarshalInt(value)
	return res, graphql.ErrorOnPath(ctx, err)
}

// split_codecs_.gotpl — unmarshal
func unmarshalNString2string(ctx context.Context, ec shardruntime.ObjectExecutionContext, value any) (any, error) {
	res, err := graphql.UnmarshalString(value)
	return res, graphql.ErrorOnPath(ctx, err)
}
