// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package nullable_root

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/executor/shardruntime"
	"github.com/vektah/gqlparser/v2/ast"
)

const splitScope = "github.com/99designs/gqlgen/codegen/testserver/splitpackages"

var type_String = &shardruntime.ObjectChildLookup{
	TypeName: "String",
	Kind:     ast.Scalar,
}

func init() {
}

// split_args_.gotpl — args for Mutation.maybeGreet
func __splitArgs_field_Mutation_maybeGreet_args(ctx context.Context, ec shardruntime.ObjectExecutionContext, rawArgs map[string]any) (map[string]any, error) {
	args := map[string]any{}
	var arg0 string
	if tmp, ok := rawArgs["name"]; ok {
		ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("name"))
		data, err := ec.UnmarshalCodec(ctx, "unmarshalNString2string", tmp)
		if err != nil {
			return nil, err
		}
		arg0 = data.(string)
	}
	args["name"] = arg0
	return args, nil
}

// split_args_.gotpl — args for Query.maybeHello
func __splitArgs_field_Query_maybeHello_args(ctx context.Context, ec shardruntime.ObjectExecutionContext, rawArgs map[string]any) (map[string]any, error) {
	args := map[string]any{}
	var arg0 string
	if tmp, ok := rawArgs["name"]; ok {
		ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("name"))
		data, err := ec.UnmarshalCodec(ctx, "unmarshalNString2string", tmp)
		if err != nil {
			return nil, err
		}
		arg0 = data.(string)
	}
	args["name"] = arg0
	return args, nil
}
