// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package nullable_root

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/executor/shardruntime"
)

func init() {
	shardruntime.RegisterFieldDef(splitScope, "Mutation", "maybeGreet", shardruntime.FieldDef{
		Resolve: func(ctx context.Context, ec shardruntime.ObjectExecutionContext, obj any) (any, error) {
			return ec.InvokeResolver(ctx, "Mutation", "maybeGreet", obj)
		},
		Directives: func(ctx context.Context, ec shardruntime.ObjectExecutionContext, obj any, next graphql.Resolver) graphql.Resolver {
			return ec.FieldMiddleware(ctx, obj, next)
		},
		MarshalCodec: "marshalOString2ᚖstring",
		NonNull:      false,
		PanicHandled: true,
		IsMethod:     true,
		IsResolver:   true,
		ArgsKey:      "field_Mutation_maybeGreet_args",
		ReturnType:   type_String,
	})
	shardruntime.RegisterFieldDef(splitScope, "Query", "maybeHello", shardruntime.FieldDef{
		Resolve: func(ctx context.Context, ec shardruntime.ObjectExecutionContext, obj any) (any, error) {
			return ec.InvokeResolver(ctx, "Query", "maybeHello", obj)
		},
		Directives: func(ctx context.Context, ec shardruntime.ObjectExecutionContext, obj any, next graphql.Resolver) graphql.Resolver {
			return ec.FieldMiddleware(ctx, obj, next)
		},
		MarshalCodec: "marshalOString2ᚖstring",
		NonNull:      false,
		PanicHandled: true,
		IsMethod:     true,
		IsResolver:   true,
		ArgsKey:      "field_Query_maybeHello_args",
		ReturnType:   type_String,
	})
}

func init() {
	shardruntime.RegisterArgs(splitScope, "field_Mutation_maybeGreet_args", __splitArgs_field_Mutation_maybeGreet_args)
	shardruntime.RegisterArgs(splitScope, "field_Query_maybeHello_args", __splitArgs_field_Query_maybeHello_args)
}
